auto_select_gpus: false
batch_size: 256
data_path: data/processed/flowers/
depth: 1
dropout_attn: 0.2
dropout_rate: 0.2
embed_dim: 128
gpus: 1
image_size: 224
lr: 0.001
max_epochs: 200
min_epochs: 1
model_dir: models/
momentum: 0.0
num_classes: 104
num_heads: 1
num_workers: 8
patch_size: 16
random_affine: false
random_gauss: false
random_hflip: false
wandb_api_key: null
