steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'train.Dockerfile', '-t', 'gcr.io/$PROJECT_ID/vit_trainer:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/vit_trainer:latest']