name: ml_ops
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - certifi=2020.6.20
  - libffi=3.4.2
  - openssl=1.1.1l
  - pip=21.2.4
  - python=3.10.0
  - setuptools=58.0.4
  - sqlite=3.37.0
  - tk=8.6.11
  - tzdata=2021e
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.0
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.11
