name: "Lint files"
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.7
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio
        pip install -r requirements.txt
    - name: Run pytest
      run: |
        pip install pytest
        pytest -v 
    - name: Run coverage html
      run: |
        pip install coverage
        coverage html
        rm htmlcov/.gitignore
    - name: Run isort and black
      run: |
        pip install isort black
        isort .
        black .
    - name: Add & Commit
      uses: EndBug/add-and-commit@v7.5.0
      with:
        default_author: github_actions
        remove: 'setup-miniconda-patched-environment.yml'


